DROP DATABASE IF EXISTS  eVoting;
CREATE DATABASE IF NOT EXISTS eVoting;

DROP TABLE IF EXISTS admin;
CREATE TABLE IF NOT EXISTS admin(
  admin_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
  fname VARCHAR (100) NOT NULL ,
  lname VARCHAR (100) NOT NULL ,
  email VARCHAR (100) NOT NULL UNIQUE ,
  phone BIGINT (11) NOT NULL,
  username VARCHAR (100) NOT NULL ,
  pword VARCHAR (100) NOT NULL

);

DROP TABLE IF EXISTS election;
CREATE TABLE IF NOT EXISTS election(
  election_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
  name VARCHAR (200) NOT NULL ,
  date DATE NOT NULL ,
  time TIME NOT NULL
);

DROP TABLE IF EXISTS contestants;
CREATE TABLE IF NOT EXISTS contestants(
  contestant_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT

);

DROP TABLE IF EXISTS posts;
CREATE TABLE IF NOT EXISTS posts(
 post_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT
);

DROP TABLE IF EXISTS voters;
CREATE TABLE IF NOT EXISTS voters(
  voter_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
);

DROP TABLE IF EXISTS legit;
CREATE TABLE IF NOT EXISTS legit(
name 
);